[2022-04-11 12:57:59,981] {processor.py:163} INFO - Started process (PID=1441) to work on /home/isedugloria/airflow/dags/test_cycles.py
[2022-04-11 12:57:59,985] {processor.py:642} INFO - Processing file /home/isedugloria/airflow/dags/test_cycles.py for tasks to queue
[2022-04-11 12:57:59,995] {logging_mixin.py:109} INFO - [2022-04-11 12:57:59,994] {dagbag.py:500} INFO - Filling up the DagBag from /home/isedugloria/airflow/dags/test_cycles.py
[2022-04-11 12:58:00,019] {logging_mixin.py:109} INFO - [2022-04-11 12:58:00,007] {dagbag.py:334} ERROR - Failed to import: /home/isedugloria/airflow/dags/test_cycles.py
Traceback (most recent call last):
  File "/home/isedugloria/demoenv/lib/python3.9/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 786, in exec_module
  File "<frozen importlib._bootstrap_external>", line 923, in get_code
  File "<frozen importlib._bootstrap_external>", line 853, in source_to_code
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/isedugloria/airflow/dags/test_cycles.py", line 21
    	dag_objects = [var for var in vars(module).values() if isinstance(var, DAG)]
TabError: inconsistent use of tabs and spaces in indentation
[2022-04-11 12:58:00,245] {processor.py:656} WARNING - No viable dags retrieved from /home/isedugloria/airflow/dags/test_cycles.py
[2022-04-11 12:58:00,365] {processor.py:171} INFO - Processing /home/isedugloria/airflow/dags/test_cycles.py took 0.430 seconds
